/* Extracts only the Fluent icons used by the app from @iconify-json/fluent
 * into src/fluent-icons.gen.ts (so the multi-MB collection never ships).
 * Run: npm run icons */
import { readFileSync, writeFileSync } from "node:fs";
import { getIconData } from "@iconify/utils";

const collection = JSON.parse(readFileSync(new URL("../node_modules/@iconify-json/fluent/icons.json", import.meta.url)));

/** App icon name → Fluent base name (the 16px regular variant is preferred, then 20px) */
const MAP = {
  inbox: "mail-inbox",
  target: "target",
  chat: "chat",
  hash: "number-symbol",
  lock: "lock-closed",
  layers: "layer",
  box: "box",
  search: "search",
  compose: "compose",
  plus: "add",
  filter: "filter",
  sliders: "options",
  chevronDown: "chevron-down",
  chevronRight: "chevron-right",
  chevronLeft: "chevron-left",
  clip: "attach",
  arrowUp: "arrow-up",
  arrowRight: "arrow-right",
  ticket: "ticket-diagonal",
  link: "link",
  unlink: "link-dismiss",
  x: "dismiss",
  check: "checkmark",
  more: "more-horizontal",
  smile: "emoji-add",
  reply: "arrow-reply",
  image: "image",
  list: "text-bullet-list-ltr",
  board: "board",
  sidebar: "panel-left",
  sun: "weather-sunny",
  moon: "weather-moon",
  bell: "alert",
  user: "person",
  users: "people",
  calendar: "calendar",
  tag: "tag",
  trash: "delete",
  copy: "copy",
  external: "open",
  bot: "bot",
  thread: "comment-multiple",
  mic: "mic",
  play: "play",
  settings: "settings",
  cmd: "keyboard",
  archive: "archive",
  circleDashed: "circle-hint",
  send: "send",
  folder: "folder",
  folderOpen: "folder-open",
  doc: "document-text",
  book: "book-open",
  share: "share",
  history: "history",
  eye: "eye",
  edit: "edit",
  team: "people-team",
  building: "building",
  restore: "arrow-counterclockwise",
  folderAdd: "folder-add",
  docAdd: "document-add",
  personSwap: "person-swap",
  shieldLock: "shield-lock",
  globe: "globe",
  mail: "mail",
  key: "key",
  signOut: "sign-out",
  download: "arrow-download",
  arrowDown: "arrow-down",
  personAdd: "person-add",
  emoji: "emoji",
  doorArrow: "door-arrow-left",
  language: "local-language",
  person: "person-circle",
};
/** Small glyphs used inside other controls */
const EXTRA = {
  caret: ["caret-down-12-filled", "caret-down-16-filled"],
  checkSmall: ["checkmark-12-filled", "checkmark-16-filled"],
  warning: ["warning-16-regular"],
  checkCircle: ["checkmark-circle-16-filled"],
};

const out = {};
const pick = (candidates) => {
  for (const n of candidates) {
    const d = getIconData(collection, n);
    if (d) return { name: n, body: d.body, width: d.width ?? collection.width ?? 16, height: d.height ?? collection.height ?? 16 };
  }
  throw new Error(`Missing Fluent icon: ${candidates.join(" | ")}`);
};
for (const [key, base] of Object.entries(MAP)) out[key] = pick([`${base}-16-regular`, `${base}-20-regular`, `${base}-24-regular`]);
for (const [key, list] of Object.entries(EXTRA)) out[key] = pick(list);

const lines = Object.entries(out).map(
  ([k, v]) => `  ${k}: { w: ${v.width}, h: ${v.height}, body: ${JSON.stringify(v.body)} }, // fluent:${v.name}`,
);
writeFileSync(
  new URL("../src/fluent-icons.gen.ts", import.meta.url),
  `/* GENERATED by scripts/gen-icons.mjs from @iconify-json/fluent (MIT) — do not edit, run \`npm run icons\`. */\n` +
    `export const FLUENT = {\n${lines.join("\n")}\n} as const;\n\nexport type FluentName = keyof typeof FLUENT;\n`,
);
console.log(`Wrote ${Object.keys(out).length} icons`);
