import "./context";
import { defineMutator, defineMutators, type Transaction } from "@rocicorp/zero";
import { z } from "zod";
import { DM_MAX_MEMBERS, dmChannelId, excerpt, mentionedUserIds, normalizeChannelName } from "../chat";
import { channelKind } from "../enums";
import { commentMutators, labelMutators, projectMutators, ticketMutators } from "./mutators-tickets";
import { assertCanManageChannel, assertCanReadChannel, assertOrgMember, isOrgAdmin, orgMembership, PermissionError } from "./permissions";
import { zql } from "./schema";

const id = z.string().min(1).max(64);
/** Channel ids are longer for direct messages (see dmChannelId) */
const channelId = z.string().min(1).max(320);
const emoji = z.string().min(1).max(32);

/*
 * Conventions
 * - Permission checks run on the server (`tx.location === "server"`): on the client the rows
 *   needed for a check may not be synced, and the server result is authoritative anyway.
 * - Ids are generated by the caller (never inside a mutator: mutators run several times).
 *   Rows owned by a (channel, user) pair use deterministic ids, e.g. `${channelId}:${userId}`.
 * - Counters (channel.last_seq, message.reply_count) are updated atomically with SQL on the
 *   server; the client mirrors them optimistically from its local store.
 */

const memberId = (channel: string, user: string) => `${channel}:${user}`;
const now = (tx: Transaction, clientTime: number) => (tx.location === "server" ? Date.now() : clientTime);

async function firstRow<T>(tx: Transaction, sql: string, params: unknown[]): Promise<T | undefined> {
  if (tx.location !== "server") return undefined;
  for (const row of await tx.dbTransaction.query(sql, params)) return row as T;
  return undefined;
}

/** Adds the user to a channel if not already a member (unread starts at the current position) */
async function ensureMembership(
  tx: Transaction,
  organizationId: string,
  channel: { id: string; lastSeq: number | null },
  userId: string,
  at: number,
) {
  const existing = await tx.run(zql.channelMember.where("id", memberId(channel.id, userId)).one());
  if (existing) return;
  await tx.mutate.channelMember.upsert({
    id: memberId(channel.id, userId),
    organizationId,
    channelId: channel.id,
    userId,
    lastReadAt: at,
    lastReadSeq: channel.lastSeq ?? 0,
    joinedAt: at,
  });
}

/** Creates `mention` notifications for users mentioned in a message who can read its channel */
async function notifyMentions(
  tx: Transaction,
  authorId: string,
  msg: { id: string; organizationId: string; channelId: string; body: string },
  alreadyNotified: readonly string[] = [],
) {
  if (tx.location !== "server") return; // notifications only matter to their recipients
  const channel = await tx.run(zql.channel.where("id", msg.channelId).related("members").one());
  if (!channel) return;
  for (const userId of mentionedUserIds(msg.body)) {
    if (userId === authorId || alreadyNotified.includes(userId)) continue;
    if (!(await orgMembership(tx, userId, msg.organizationId))) continue;
    // Private channels and DMs: only notify people who can read the message
    if (channel.kind !== "public" && !channel.members.some((m) => m.userId === userId)) continue;
    await tx.mutate.notification.upsert({
      id: `${msg.id}:mention:${userId}`,
      organizationId: msg.organizationId,
      userId,
      actorId: authorId,
      kind: "mention",
      ticketId: null,
      messageId: msg.id,
      channelId: msg.channelId,
      docId: null,
      folderId: null,
      body: excerpt(msg.body),
      createdAt: Date.now(),
      readAt: null,
    });
  }
}

const attachmentInput = z.object({
  id,
  kind: z.enum(["image", "file", "audio"]),
  name: z.string().max(255),
  mimeType: z.string().max(255),
  size: z.number().int().nonnegative(),
  storageKey: z.string().max(512),
  thumbKey: z.string().max(512).nullable(),
  width: z.number().int().nullable(),
  height: z.number().int().nullable(),
  createdAt: z.number(),
});

export const mutators = defineMutators({
  channels: {
    create: defineMutator(
      z.object({
        id,
        organizationId: id,
        name: z.string().trim().min(1).max(80),
        kind: channelKind.exclude(["dm"]),
        topic: z.string().max(500).nullable().optional(),
        projectId: id.nullable().optional(),
        /** Other people to add right away (private channels) */
        memberIds: z.array(id).max(200).optional(),
        createdAt: z.number(),
      }),
      async ({ tx, ctx, args }) => {
        if (tx.location === "server") {
          await assertOrgMember(tx, ctx.userID, args.organizationId);
          if (args.projectId) {
            const p = await tx.run(zql.project.where("id", args.projectId).where("organizationId", args.organizationId).one());
            if (!p) throw new PermissionError("Unknown project");
          }
        }
        const name = normalizeChannelName(args.name);
        if (!name) throw new Error("Channel name is required");
        await tx.mutate.channel.insert({
          id: args.id,
          organizationId: args.organizationId,
          kind: args.kind,
          name,
          topic: args.topic?.trim() || null,
          projectId: args.projectId ?? null,
          createdBy: ctx.userID,
          createdAt: args.createdAt,
          archivedAt: null,
          lastSeq: 0,
          lastMessageAt: null,
        });
        const channel = { id: args.id, lastSeq: 0 };
        // The creator is always a member (required for private channels, harmless for public ones)
        await ensureMembership(tx, args.organizationId, channel, ctx.userID, args.createdAt);
        for (const userId of new Set(args.memberIds ?? [])) {
          if (userId === ctx.userID) continue;
          if (tx.location === "server" && !(await orgMembership(tx, userId, args.organizationId))) continue;
          await ensureMembership(tx, args.organizationId, channel, userId, args.createdAt);
        }
      },
    ),

    /** Rename, change topic or default project (creator, owner, admins) */
    update: defineMutator(
      z.object({
        organizationId: id,
        channelId,
        name: z.string().trim().min(1).max(80).optional(),
        topic: z.string().max(500).nullable().optional(),
        projectId: id.nullable().optional(),
      }),
      async ({ tx, ctx, args }) => {
        if (tx.location === "server") {
          await assertCanManageChannel(tx, ctx.userID, args.organizationId, args.channelId);
          if (args.projectId) {
            const p = await tx.run(zql.project.where("id", args.projectId).where("organizationId", args.organizationId).one());
            if (!p) throw new PermissionError("Unknown project");
          }
        }
        await tx.mutate.channel.update({
          id: args.channelId,
          name: args.name === undefined ? undefined : normalizeChannelName(args.name),
          topic: args.topic === undefined ? undefined : args.topic?.trim() || null,
          projectId: args.projectId,
        });
      },
    ),

    /** Archive (read-only, hidden from the sidebar) or restore a channel */
    archive: defineMutator(
      z.object({ organizationId: id, channelId, archived: z.boolean(), at: z.number() }),
      async ({ tx, ctx, args }) => {
        if (tx.location === "server") await assertCanManageChannel(tx, ctx.userID, args.organizationId, args.channelId);
        await tx.mutate.channel.update({ id: args.channelId, archivedAt: args.archived ? now(tx, args.at) : null });
      },
    ),

    /** Join a public channel */
    join: defineMutator(z.object({ organizationId: id, channelId, at: z.number() }), async ({ tx, ctx, args }) => {
      const ch =
        tx.location === "server"
          ? await assertCanReadChannel(tx, ctx.userID, args.organizationId, args.channelId)
          : await tx.run(zql.channel.where("id", args.channelId).one());
      if (!ch) return;
      if (ch.kind !== "public") throw new PermissionError("Only public channels can be joined");
      await ensureMembership(tx, args.organizationId, ch, ctx.userID, args.at);
    }),

    /** Leave a channel (not a direct conversation) */
    leave: defineMutator(z.object({ organizationId: id, channelId }), async ({ tx, ctx, args }) => {
      if (tx.location === "server") {
        const ch = await assertCanReadChannel(tx, ctx.userID, args.organizationId, args.channelId);
        if (ch.kind === "dm") throw new PermissionError("Direct conversations cannot be left");
      }
      await tx.mutate.channelMember.delete({ id: memberId(args.channelId, ctx.userID) });
    }),

    /** Add people to a channel. Private channels: only their members can add someone. */
    addMembers: defineMutator(
      z.object({ organizationId: id, channelId, userIds: z.array(id).min(1).max(200), at: z.number() }),
      async ({ tx, ctx, args }) => {
        const ch =
          tx.location === "server"
            ? await assertCanReadChannel(tx, ctx.userID, args.organizationId, args.channelId)
            : await tx.run(zql.channel.where("id", args.channelId).one());
        if (!ch) return;
        if (tx.location === "server") {
          if (ch.kind === "dm") throw new PermissionError("Start a new conversation instead");
          if (ch.kind === "private" && !(await tx.run(zql.channelMember.where("id", memberId(ch.id, ctx.userID)).one())))
            throw new PermissionError("Only members can add people to a private channel");
        }
        for (const userId of new Set(args.userIds)) {
          if (tx.location === "server" && !(await orgMembership(tx, userId, args.organizationId))) continue;
          await ensureMembership(tx, args.organizationId, ch, userId, args.at);
        }
      },
    ),

    /**
     * Open (or create) the direct conversation between the current user and `userIds`.
     * The id is deterministic (dmChannelId), so opening it twice is a no-op.
     */
    openDm: defineMutator(
      z.object({
        organizationId: id,
        userIds: z
          .array(id)
          .min(1)
          .max(DM_MAX_MEMBERS - 1),
        at: z.number(),
      }),
      async ({ tx, ctx, args }) => {
        const members = [...new Set([ctx.userID, ...args.userIds])];
        const dmId = dmChannelId(args.organizationId, members);
        if (tx.location === "server") {
          for (const userId of members) {
            if (!(await orgMembership(tx, userId, args.organizationId))) throw new PermissionError("Everyone must be in the organization");
          }
        }
        const existing = await tx.run(zql.channel.where("id", dmId).one());
        if (!existing) {
          await tx.mutate.channel.insert({
            id: dmId,
            organizationId: args.organizationId,
            kind: "dm",
            name: "",
            topic: null,
            projectId: null,
            createdBy: ctx.userID,
            createdAt: args.at,
            archivedAt: null,
            lastSeq: 0,
            lastMessageAt: null,
          });
        }
        const channel = { id: dmId, lastSeq: existing?.lastSeq ?? 0 };
        for (const userId of members) await ensureMembership(tx, args.organizationId, channel, userId, args.at);
      },
    ),

    /** Marks a channel as read up to `seq` (never moves backwards) */
    markRead: defineMutator(z.object({ channelId, seq: z.number().int().nonnegative(), at: z.number() }), async ({ tx, ctx, args }) => {
      const m = await tx.run(zql.channelMember.where("id", memberId(args.channelId, ctx.userID)).one());
      if (!m) return; // not a member (e.g. previewing a public channel): nothing to track
      if ((m.lastReadSeq ?? 0) >= args.seq) return;
      const ch = await tx.run(zql.channel.where("id", args.channelId).one());
      const seq = Math.min(args.seq, ch?.lastSeq ?? args.seq);
      await tx.mutate.channelMember.update({ id: m.id, lastReadSeq: seq, lastReadAt: now(tx, args.at) });
    }),
  },

  messages: {
    send: defineMutator(
      z
        .object({
          id,
          organizationId: id,
          channelId,
          body: z.string().max(20_000),
          parentId: id.nullable().optional(),
          /** Files uploaded beforehand through POST /api/uploads */
          attachments: z.array(attachmentInput).max(10).optional(),
          createdAt: z.number(),
        })
        .refine((a) => a.body.trim().length > 0 || (a.attachments?.length ?? 0) > 0, "Empty message"),
      async ({ tx, ctx, args }) => {
        const at = now(tx, args.createdAt);
        const ch =
          tx.location === "server"
            ? await assertCanReadChannel(tx, ctx.userID, args.organizationId, args.channelId)
            : await tx.run(zql.channel.where("id", args.channelId).one());
        if (!ch) return;
        if (ch.archivedAt) throw new PermissionError("This channel is archived");

        if (tx.location === "server" && ch.kind !== "public") {
          // Posting in a public channel joins it; private channels and DMs require membership
          const mine = await tx.run(zql.channelMember.where("id", memberId(ch.id, ctx.userID)).one());
          if (!mine) throw new PermissionError("Not a member of this channel");
        }

        let parent: { id: string; replyCount: number | null } | undefined;
        if (args.parentId) {
          const p = await tx.run(zql.message.where("id", args.parentId).one());
          if (tx.location === "server" && (!p || p.channelId !== ch.id)) throw new PermissionError("Unknown thread");
          if (p?.parentId) throw new Error("Replies cannot have replies");
          parent = p;
        }

        // Channel sequence for top-level messages (unread counters)
        let seq: number | null = null;
        if (!args.parentId) {
          const row = await firstRow<{ last_seq: number }>(
            tx,
            "update channel set last_seq = last_seq + 1, last_message_at = now() where id = $1 returning last_seq",
            [ch.id],
          );
          seq = row ? Number(row.last_seq) : (ch.lastSeq ?? 0) + 1;
          if (tx.location !== "server") await tx.mutate.channel.update({ id: ch.id, lastSeq: seq, lastMessageAt: at });
        } else if (parent) {
          if (tx.location === "server") {
            await tx.dbTransaction.query("update message set reply_count = reply_count + 1, last_reply_at = now() where id = $1", [
              parent.id,
            ]);
          } else {
            await tx.mutate.message.update({ id: parent.id, replyCount: (parent.replyCount ?? 0) + 1, lastReplyAt: at });
          }
        }

        await tx.mutate.message.insert({
          id: args.id,
          organizationId: args.organizationId,
          channelId: ch.id,
          authorId: ctx.userID,
          parentId: args.parentId ?? null,
          body: args.body.trim(),
          seq,
          replyCount: 0,
          ticketCount: 0,
          lastReplyAt: null,
          // The server clock is authoritative for ordering
          createdAt: at,
          editedAt: null,
          deletedAt: null,
        });

        // The author has read everything up to their own message (joins public channels on first post)
        await ensureMembership(tx, args.organizationId, { id: ch.id, lastSeq: seq ?? ch.lastSeq }, ctx.userID, at);
        if (seq !== null) await tx.mutate.channelMember.update({ id: memberId(ch.id, ctx.userID), lastReadSeq: seq, lastReadAt: at });

        // Attach uploaded files: only the uploader's own pending files of this channel
        for (const a of args.attachments ?? []) {
          if (tx.location === "server") {
            const row = await tx.run(zql.attachment.where("id", a.id).one());
            if (!row || row.uploadedBy !== ctx.userID || row.channelId !== ch.id || row.messageId !== null)
              throw new PermissionError("Invalid attachment");
            await tx.mutate.attachment.update({ id: a.id, messageId: args.id });
          } else {
            await tx.mutate.attachment.upsert({
              ...a,
              organizationId: args.organizationId,
              messageId: args.id,
              channelId: ch.id,
              uploadedBy: ctx.userID,
            });
          }
        }

        await notifyMentions(tx, ctx.userID, { id: args.id, organizationId: args.organizationId, channelId: ch.id, body: args.body });
      },
    ),

    /** Edit your own message */
    edit: defineMutator(
      z.object({ organizationId: id, id, body: z.string().trim().min(1).max(20_000), at: z.number() }),
      async ({ tx, ctx, args }) => {
        const msg = await tx.run(zql.message.where("id", args.id).one());
        if (!msg) return;
        if (tx.location === "server") {
          await assertCanReadChannel(tx, ctx.userID, args.organizationId, msg.channelId);
          if (msg.authorId !== ctx.userID) throw new PermissionError("You can only edit your own messages");
          if (msg.deletedAt) throw new PermissionError("This message was deleted");
        }
        await tx.mutate.message.update({ id: msg.id, body: args.body, editedAt: now(tx, args.at) });
        await notifyMentions(tx, ctx.userID, { ...msg, body: args.body }, mentionedUserIds(msg.body));
      },
    ),

    /** Delete a message (author, or organization owner/admin). Soft delete keeps threads intact. */
    delete: defineMutator(z.object({ organizationId: id, id, at: z.number() }), async ({ tx, ctx, args }) => {
      const msg = await tx.run(zql.message.where("id", args.id).related("attachments").one());
      if (!msg || msg.deletedAt) return;
      if (tx.location === "server") {
        await assertCanReadChannel(tx, ctx.userID, args.organizationId, msg.channelId);
        if (msg.authorId !== ctx.userID) {
          const m = await orgMembership(tx, ctx.userID, args.organizationId);
          if (!isOrgAdmin(m?.role)) throw new PermissionError("You can only delete your own messages");
        }
      }
      await tx.mutate.message.update({ id: msg.id, body: "", deletedAt: now(tx, args.at) });
      for (const a of msg.attachments) await tx.mutate.attachment.delete({ id: a.id });
      if (msg.parentId) {
        if (tx.location === "server") {
          await tx.dbTransaction.query("update message set reply_count = greatest(reply_count - 1, 0) where id = $1", [msg.parentId]);
        } else {
          const parent = await tx.run(zql.message.where("id", msg.parentId).one());
          if (parent) await tx.mutate.message.update({ id: parent.id, replyCount: Math.max((parent.replyCount ?? 0) - 1, 0) });
        }
      }
    }),
  },

  reactions: {
    /** Add or remove an emoji reaction on a message */
    toggle: defineMutator(z.object({ organizationId: id, messageId: id, emoji, at: z.number() }), async ({ tx, ctx, args }) => {
      const msg = await tx.run(zql.message.where("id", args.messageId).one());
      if (!msg) return;
      if (tx.location === "server") {
        await assertCanReadChannel(tx, ctx.userID, args.organizationId, msg.channelId);
        if (msg.deletedAt) throw new PermissionError("This message was deleted");
      }
      const reactionId = `${args.messageId}:${ctx.userID}:${args.emoji}`;
      const existing = await tx.run(zql.reaction.where("id", reactionId).one());
      if (existing) {
        await tx.mutate.reaction.delete({ id: reactionId });
      } else {
        await tx.mutate.reaction.insert({
          id: reactionId,
          organizationId: args.organizationId,
          messageId: args.messageId,
          commentId: null,
          userId: ctx.userID,
          emoji: args.emoji,
          createdAt: now(tx, args.at),
        });
      }
    }),
  },

  projects: projectMutators,
  labels: labelMutators,
  tickets: ticketMutators,
  comments: commentMutators,
});
