// @generated drizzle-zero signature:sha256:5bb6adc19e157b5f265122fcc5edcf3c6ffe3aa8f2490f1d3d0c5460a6319fa4
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const accessGrantTable = {
  name: "accessGrant",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    folderId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "folder_id",
    },
    docId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "doc_id",
    },
    principalType: {
      type: "string",
      optional: false,
      customType: null as unknown as "team" | "user" | "org",
      serverName: "principal_type",
    },
    principalId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "principal_id",
    },
    level: {
      type: "string",
      optional: false,
      customType: null as unknown as "read" | "edit" | "manage",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "access_grant",
} as const;
const activityTable = {
  name: "activity",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    ticketId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "ticket_id",
    },
    actorId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "actor_id",
    },
    kind: {
      type: "string",
      optional: false,
      customType: null as unknown as
        | "project"
        | "description"
        | "status"
        | "labels"
        | "title"
        | "priority"
        | "assignee"
        | "created"
        | "linked_messages"
        | "unlinked_messages",
    },
    fromValue: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "from_value",
    },
    toValue: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "to_value",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const attachmentTable = {
  name: "attachment",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    messageId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "message_id",
    },
    channelId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "channel_id",
    },
    kind: {
      type: "string",
      optional: false,
      customType: null as unknown as "image" | "file" | "audio",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    mimeType: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "mime_type",
    },
    size: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    storageKey: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "storage_key",
    },
    thumbKey: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "thumb_key",
    },
    width: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    height: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    uploadedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "uploaded_by",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const channelTable = {
  name: "channel",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    kind: {
      type: "string",
      optional: false,
      customType: null as unknown as "public" | "private" | "dm",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    topic: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    projectId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "project_id",
    },
    createdBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "created_by",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    archivedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "archived_at",
    },
    lastSeq: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "last_seq",
    },
    lastMessageAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "last_message_at",
    },
  },
  primaryKey: ["id"],
} as const;
const channelMemberTable = {
  name: "channelMember",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    channelId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "channel_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    lastReadAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "last_read_at",
    },
    lastReadSeq: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "last_read_seq",
    },
    joinedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "channel_member",
} as const;
const commentTable = {
  name: "comment",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    ticketId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "ticket_id",
    },
    authorId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "author_id",
    },
    body: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    editedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "edited_at",
    },
  },
  primaryKey: ["id"],
} as const;
const docTable = {
  name: "doc",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    folderId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "folder_id",
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    content: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    inheritGrants: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "inherit_grants",
    },
    source: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "created_by",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "updated_by",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const docFolderTable = {
  name: "docFolder",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    parentId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "parent_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    inheritGrants: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "inherit_grants",
    },
    createdBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "created_by",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "doc_folder",
} as const;
const docVersionTable = {
  name: "docVersion",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    docId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "doc_id",
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    content: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    authorId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "author_id",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "doc_version",
} as const;
const invitationTable = {
  name: "invitation",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    teamId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "team_id",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    expiresAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "expires_at",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    inviterId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "inviter_id",
    },
  },
  primaryKey: ["id"],
} as const;
const labelTable = {
  name: "label",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    color: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const memberTable = {
  name: "member",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const messageTable = {
  name: "message",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    channelId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "channel_id",
    },
    authorId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "author_id",
    },
    parentId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "parent_id",
    },
    body: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    seq: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    replyCount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "reply_count",
    },
    ticketCount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "ticket_count",
    },
    lastReplyAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "last_reply_at",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    editedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "edited_at",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "deleted_at",
    },
  },
  primaryKey: ["id"],
} as const;
const notificationTable = {
  name: "notification",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    actorId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "actor_id",
    },
    kind: {
      type: "string",
      optional: false,
      customType: null as unknown as
        | "comment"
        | "mention"
        | "ticket_assigned"
        | "ticket_status"
        | "ticket_from_my_message"
        | "access_request",
    },
    ticketId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "ticket_id",
    },
    messageId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "message_id",
    },
    channelId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "channel_id",
    },
    docId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "doc_id",
    },
    folderId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "folder_id",
    },
    body: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    readAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "read_at",
    },
    archivedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "archived_at",
    },
  },
  primaryKey: ["id"],
} as const;
const notificationSettingTable = {
  name: "notificationSetting",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    mutedKinds: {
      type: "json",
      optional: true,
      customType: null as unknown as (
        | "comment"
        | "mention"
        | "ticket_assigned"
        | "ticket_status"
        | "ticket_from_my_message"
        | "access_request"
      )[],
      serverName: "muted_kinds",
    },
    browserEnabled: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "browser_enabled",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "notification_setting",
} as const;
const organizationTable = {
  name: "organization",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    slug: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    logo: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    metadata: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const projectTable = {
  name: "project",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    key: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    color: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    visibility: {
      type: "string",
      optional: true,
      customType: null as unknown as "members" | "org",
    },
    ticketCounter: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "ticket_counter",
    },
    createdBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "created_by",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    archivedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "archived_at",
    },
  },
  primaryKey: ["id"],
} as const;
const projectMemberTable = {
  name: "projectMember",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    projectId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "project_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    role: {
      type: "string",
      optional: false,
      customType: null as unknown as
        "lead" | "contributor" | "reporter" | "viewer",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "project_member",
} as const;
const reactionTable = {
  name: "reaction",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    messageId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "message_id",
    },
    commentId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "comment_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    emoji: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const teamTable = {
  name: "team",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    memberCount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "member_count",
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const teamMemberTable = {
  name: "teamMember",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    teamId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "team_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    membershipKey: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "membership_key",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "team_member",
} as const;
const ticketTable = {
  name: "ticket",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    projectId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "project_id",
    },
    number: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    status: {
      type: "string",
      optional: false,
      customType: null as unknown as
        | "triage"
        | "backlog"
        | "todo"
        | "in_progress"
        | "in_review"
        | "done"
        | "canceled",
    },
    priority: {
      type: "number",
      optional: true,
      customType: null as unknown as 0 | 1 | 2 | 3 | 4,
    },
    assigneeId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "assignee_id",
    },
    creatorId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "creator_id",
    },
    createdVia: {
      type: "string",
      optional: true,
      customType: null as unknown as "app" | "mcp",
      serverName: "created_via",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
    completedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "completed_at",
    },
  },
  primaryKey: ["id"],
} as const;
const ticketAliasTable = {
  name: "ticketAlias",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    projectId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "project_id",
    },
    number: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    ticketId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "ticket_id",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "ticket_alias",
} as const;
const ticketLabelTable = {
  name: "ticketLabel",
  columns: {
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    ticketId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "ticket_id",
    },
    labelId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "label_id",
    },
  },
  primaryKey: ["ticketId", "labelId"],
  serverName: "ticket_label",
} as const;
const ticketSourceTable = {
  name: "ticketSource",
  columns: {
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    ticketId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "ticket_id",
    },
    messageId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "message_id",
    },
    addedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "added_by",
    },
    addedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "added_at",
    },
  },
  primaryKey: ["ticketId", "messageId"],
  serverName: "ticket_source",
} as const;
const userTable = {
  name: "user",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    image: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const accessGrantRelationships = {
  folder: [
    {
      sourceField: ["folderId"],
      destField: ["id"],
      destSchema: "docFolder",
      cardinality: "one",
    },
  ],
  doc: [
    {
      sourceField: ["docId"],
      destField: ["id"],
      destSchema: "doc",
      cardinality: "one",
    },
  ],
} as const;
const activityRelationships = {
  ticket: [
    {
      sourceField: ["ticketId"],
      destField: ["id"],
      destSchema: "ticket",
      cardinality: "one",
    },
  ],
  actor: [
    {
      sourceField: ["actorId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const attachmentRelationships = {
  message: [
    {
      sourceField: ["messageId"],
      destField: ["id"],
      destSchema: "message",
      cardinality: "one",
    },
  ],
  channel: [
    {
      sourceField: ["channelId"],
      destField: ["id"],
      destSchema: "channel",
      cardinality: "one",
    },
  ],
} as const;
const channelMemberRelationships = {
  channel: [
    {
      sourceField: ["channelId"],
      destField: ["id"],
      destSchema: "channel",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const channelRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  project: [
    {
      sourceField: ["projectId"],
      destField: ["id"],
      destSchema: "project",
      cardinality: "one",
    },
  ],
  members: [
    {
      sourceField: ["id"],
      destField: ["channelId"],
      destSchema: "channelMember",
      cardinality: "many",
    },
  ],
  messages: [
    {
      sourceField: ["id"],
      destField: ["channelId"],
      destSchema: "message",
      cardinality: "many",
    },
  ],
} as const;
const commentRelationships = {
  ticket: [
    {
      sourceField: ["ticketId"],
      destField: ["id"],
      destSchema: "ticket",
      cardinality: "one",
    },
  ],
  author: [
    {
      sourceField: ["authorId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  reactions: [
    {
      sourceField: ["id"],
      destField: ["commentId"],
      destSchema: "reaction",
      cardinality: "many",
    },
  ],
} as const;
const docFolderRelationships = {
  parent: [
    {
      sourceField: ["parentId"],
      destField: ["id"],
      destSchema: "docFolder",
      cardinality: "one",
    },
  ],
  children: [
    {
      sourceField: ["id"],
      destField: ["parentId"],
      destSchema: "docFolder",
      cardinality: "many",
    },
  ],
  docs: [
    {
      sourceField: ["id"],
      destField: ["folderId"],
      destSchema: "doc",
      cardinality: "many",
    },
  ],
  grants: [
    {
      sourceField: ["id"],
      destField: ["folderId"],
      destSchema: "accessGrant",
      cardinality: "many",
    },
  ],
} as const;
const docRelationships = {
  folder: [
    {
      sourceField: ["folderId"],
      destField: ["id"],
      destSchema: "docFolder",
      cardinality: "one",
    },
  ],
  versions: [
    {
      sourceField: ["id"],
      destField: ["docId"],
      destSchema: "docVersion",
      cardinality: "many",
    },
  ],
  grants: [
    {
      sourceField: ["id"],
      destField: ["docId"],
      destSchema: "accessGrant",
      cardinality: "many",
    },
  ],
} as const;
const docVersionRelationships = {
  doc: [
    {
      sourceField: ["docId"],
      destField: ["id"],
      destSchema: "doc",
      cardinality: "one",
    },
  ],
  author: [
    {
      sourceField: ["authorId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const invitationRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  inviter: [
    {
      sourceField: ["inviterId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const labelRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
} as const;
const memberRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const messageRelationships = {
  channel: [
    {
      sourceField: ["channelId"],
      destField: ["id"],
      destSchema: "channel",
      cardinality: "one",
    },
  ],
  author: [
    {
      sourceField: ["authorId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  parent: [
    {
      sourceField: ["parentId"],
      destField: ["id"],
      destSchema: "message",
      cardinality: "one",
    },
  ],
  replies: [
    {
      sourceField: ["id"],
      destField: ["parentId"],
      destSchema: "message",
      cardinality: "many",
    },
  ],
  attachments: [
    {
      sourceField: ["id"],
      destField: ["messageId"],
      destSchema: "attachment",
      cardinality: "many",
    },
  ],
  reactions: [
    {
      sourceField: ["id"],
      destField: ["messageId"],
      destSchema: "reaction",
      cardinality: "many",
    },
  ],
  ticketSources: [
    {
      sourceField: ["id"],
      destField: ["messageId"],
      destSchema: "ticketSource",
      cardinality: "many",
    },
  ],
} as const;
const notificationRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  actor: [
    {
      sourceField: ["actorId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  ticket: [
    {
      sourceField: ["ticketId"],
      destField: ["id"],
      destSchema: "ticket",
      cardinality: "one",
    },
  ],
  message: [
    {
      sourceField: ["messageId"],
      destField: ["id"],
      destSchema: "message",
      cardinality: "one",
    },
  ],
  channel: [
    {
      sourceField: ["channelId"],
      destField: ["id"],
      destSchema: "channel",
      cardinality: "one",
    },
  ],
} as const;
const notificationSettingRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const organizationRelationships = {
  members: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "member",
      cardinality: "many",
    },
  ],
  teams: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "team",
      cardinality: "many",
    },
  ],
  invitations: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "invitation",
      cardinality: "many",
    },
  ],
  projects: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "project",
      cardinality: "many",
    },
  ],
  channels: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "channel",
      cardinality: "many",
    },
  ],
  labels: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "label",
      cardinality: "many",
    },
  ],
  tickets: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "ticket",
      cardinality: "many",
    },
  ],
} as const;
const projectMemberRelationships = {
  project: [
    {
      sourceField: ["projectId"],
      destField: ["id"],
      destSchema: "project",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const projectRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  members: [
    {
      sourceField: ["id"],
      destField: ["projectId"],
      destSchema: "projectMember",
      cardinality: "many",
    },
  ],
  tickets: [
    {
      sourceField: ["id"],
      destField: ["projectId"],
      destSchema: "ticket",
      cardinality: "many",
    },
  ],
  aliases: [
    {
      sourceField: ["id"],
      destField: ["projectId"],
      destSchema: "ticketAlias",
      cardinality: "many",
    },
  ],
} as const;
const reactionRelationships = {
  message: [
    {
      sourceField: ["messageId"],
      destField: ["id"],
      destSchema: "message",
      cardinality: "one",
    },
  ],
  comment: [
    {
      sourceField: ["commentId"],
      destField: ["id"],
      destSchema: "comment",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const teamMemberRelationships = {
  team: [
    {
      sourceField: ["teamId"],
      destField: ["id"],
      destSchema: "team",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const teamRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  members: [
    {
      sourceField: ["id"],
      destField: ["teamId"],
      destSchema: "teamMember",
      cardinality: "many",
    },
  ],
} as const;
const ticketAliasRelationships = {
  ticket: [
    {
      sourceField: ["ticketId"],
      destField: ["id"],
      destSchema: "ticket",
      cardinality: "one",
    },
  ],
  project: [
    {
      sourceField: ["projectId"],
      destField: ["id"],
      destSchema: "project",
      cardinality: "one",
    },
  ],
} as const;
const ticketLabelRelationships = {
  ticket: [
    {
      sourceField: ["ticketId"],
      destField: ["id"],
      destSchema: "ticket",
      cardinality: "one",
    },
  ],
  label: [
    {
      sourceField: ["labelId"],
      destField: ["id"],
      destSchema: "label",
      cardinality: "one",
    },
  ],
} as const;
const ticketRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  project: [
    {
      sourceField: ["projectId"],
      destField: ["id"],
      destSchema: "project",
      cardinality: "one",
    },
  ],
  aliases: [
    {
      sourceField: ["id"],
      destField: ["ticketId"],
      destSchema: "ticketAlias",
      cardinality: "many",
    },
  ],
  assignee: [
    {
      sourceField: ["assigneeId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  creator: [
    {
      sourceField: ["creatorId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  labels: [
    {
      sourceField: ["id"],
      destField: ["ticketId"],
      destSchema: "ticketLabel",
      cardinality: "many",
    },
  ],
  sources: [
    {
      sourceField: ["id"],
      destField: ["ticketId"],
      destSchema: "ticketSource",
      cardinality: "many",
    },
  ],
  comments: [
    {
      sourceField: ["id"],
      destField: ["ticketId"],
      destSchema: "comment",
      cardinality: "many",
    },
  ],
  activities: [
    {
      sourceField: ["id"],
      destField: ["ticketId"],
      destSchema: "activity",
      cardinality: "many",
    },
  ],
} as const;
const ticketSourceRelationships = {
  ticket: [
    {
      sourceField: ["ticketId"],
      destField: ["id"],
      destSchema: "ticket",
      cardinality: "one",
    },
  ],
  message: [
    {
      sourceField: ["messageId"],
      destField: ["id"],
      destSchema: "message",
      cardinality: "one",
    },
  ],
} as const;
const userRelationships = {
  memberships: [
    {
      sourceField: ["id"],
      destField: ["userId"],
      destSchema: "member",
      cardinality: "many",
    },
  ],
  teamMemberships: [
    {
      sourceField: ["id"],
      destField: ["userId"],
      destSchema: "teamMember",
      cardinality: "many",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    accessGrant: accessGrantTable,
    activity: activityTable,
    attachment: attachmentTable,
    channel: channelTable,
    channelMember: channelMemberTable,
    comment: commentTable,
    doc: docTable,
    docFolder: docFolderTable,
    docVersion: docVersionTable,
    invitation: invitationTable,
    label: labelTable,
    member: memberTable,
    message: messageTable,
    notification: notificationTable,
    notificationSetting: notificationSettingTable,
    organization: organizationTable,
    project: projectTable,
    projectMember: projectMemberTable,
    reaction: reactionTable,
    team: teamTable,
    teamMember: teamMemberTable,
    ticket: ticketTable,
    ticketAlias: ticketAliasTable,
    ticketLabel: ticketLabelTable,
    ticketSource: ticketSourceTable,
    user: userTable,
  },
  relationships: {
    accessGrant: accessGrantRelationships,
    activity: activityRelationships,
    attachment: attachmentRelationships,
    channelMember: channelMemberRelationships,
    channel: channelRelationships,
    comment: commentRelationships,
    docFolder: docFolderRelationships,
    doc: docRelationships,
    docVersion: docVersionRelationships,
    invitation: invitationRelationships,
    label: labelRelationships,
    member: memberRelationships,
    message: messageRelationships,
    notification: notificationRelationships,
    notificationSetting: notificationSettingRelationships,
    organization: organizationRelationships,
    projectMember: projectMemberRelationships,
    project: projectRelationships,
    reaction: reactionRelationships,
    teamMember: teamMemberRelationships,
    team: teamRelationships,
    ticketAlias: ticketAliasRelationships,
    ticketLabel: ticketLabelRelationships,
    ticket: ticketRelationships,
    ticketSource: ticketSourceRelationships,
    user: userRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "accessGrant" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AccessGrant = Row<(typeof schema)["tables"]["accessGrant"]>;
/**
 * Represents a row from the "activity" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Activity = Row<(typeof schema)["tables"]["activity"]>;
/**
 * Represents a row from the "attachment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Attachment = Row<(typeof schema)["tables"]["attachment"]>;
/**
 * Represents a row from the "channel" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Channel = Row<(typeof schema)["tables"]["channel"]>;
/**
 * Represents a row from the "channelMember" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ChannelMember = Row<(typeof schema)["tables"]["channelMember"]>;
/**
 * Represents a row from the "comment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Comment = Row<(typeof schema)["tables"]["comment"]>;
/**
 * Represents a row from the "doc" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Doc = Row<(typeof schema)["tables"]["doc"]>;
/**
 * Represents a row from the "docFolder" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type DocFolder = Row<(typeof schema)["tables"]["docFolder"]>;
/**
 * Represents a row from the "docVersion" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type DocVersion = Row<(typeof schema)["tables"]["docVersion"]>;
/**
 * Represents a row from the "invitation" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Invitation = Row<(typeof schema)["tables"]["invitation"]>;
/**
 * Represents a row from the "label" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Label = Row<(typeof schema)["tables"]["label"]>;
/**
 * Represents a row from the "member" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Member = Row<(typeof schema)["tables"]["member"]>;
/**
 * Represents a row from the "message" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Message = Row<(typeof schema)["tables"]["message"]>;
/**
 * Represents a row from the "notification" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Notification = Row<(typeof schema)["tables"]["notification"]>;
/**
 * Represents a row from the "notificationSetting" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type NotificationSetting = Row<
  (typeof schema)["tables"]["notificationSetting"]
>;
/**
 * Represents a row from the "organization" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Organization = Row<(typeof schema)["tables"]["organization"]>;
/**
 * Represents a row from the "project" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Project = Row<(typeof schema)["tables"]["project"]>;
/**
 * Represents a row from the "projectMember" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ProjectMember = Row<(typeof schema)["tables"]["projectMember"]>;
/**
 * Represents a row from the "reaction" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Reaction = Row<(typeof schema)["tables"]["reaction"]>;
/**
 * Represents a row from the "team" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Team = Row<(typeof schema)["tables"]["team"]>;
/**
 * Represents a row from the "teamMember" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TeamMember = Row<(typeof schema)["tables"]["teamMember"]>;
/**
 * Represents a row from the "ticket" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Ticket = Row<(typeof schema)["tables"]["ticket"]>;
/**
 * Represents a row from the "ticketAlias" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TicketAlias = Row<(typeof schema)["tables"]["ticketAlias"]>;
/**
 * Represents a row from the "ticketLabel" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TicketLabel = Row<(typeof schema)["tables"]["ticketLabel"]>;
/**
 * Represents a row from the "ticketSource" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TicketSource = Row<(typeof schema)["tables"]["ticketSource"]>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["user"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
